news_sites:
  elheraldo:
    url: https://www.elheraldo.co
    queries:
      homepage_article_links: '.titulo a'
      article_body: '.description p'
      article_title: '.title h1'
  elpais:
    url: https://elpais.com
    queries:
      homepage_article_links: '.headline a'
      article_body: '.article_body'
      article_title: '#article_header h1'
  # washingtonpost:
  #   url: https://www.washingtonpost.com
  #   queries:
  #     homepage_article_links: '.headline a'
  #     article_body: '.topper-headline h1'
  #     article_title: 'article.paywall'